export const FETCH_ERROR = 'FETCH_ERROR';

export const REQUEST_EAN_CODE_REPORT = 'REQUEST_EAN_CODE_REPORT';
export const RECEIVE_EAN_CODE_REPORT = 'RECEIVE_EAN_CODE_REPORT';

export const REQUEST_TARIFFS = 'REQUEST_CURRENCIES';
export const RECEIVE_TARIFFS = 'RECEIVE_CURRENCIES';
