export const FETCH_ERROR = 'FETCH_ERROR';

export const REQUEST_EAN_CODE_REPORT = 'REQUEST_EAN_CODE_REPORT';
export const RECEIVE_EAN_CODE_REPORT = 'RECEIVE_EAN_CODE_REPORT';

export const REQUEST_CARTON_DETAILS_REPORT = 'REQUEST_CARTON_DETAILS_REPORT';
export const RECEIVE_CARTON_DETAILS_REPORT = 'RECEIVE_CARTON_DETAILS_REPORT';