export const FETCH_ERROR = 'FETCH_ERROR';

export const REQUEST_EAN_CODE_REPORT = 'REQUEST_EAN_CODE_REPORT';
export const RECEIVE_EAN_CODE_REPORT = 'RECEIVE_EAN_CODE_REPORT';

export const REQUEST_CARTON_DETAILS_REPORT = 'REQUEST_CARTON_DETAILS_REPORT';
export const RECEIVE_CARTON_DETAILS_REPORT = 'RECEIVE_CARTON_DETAILS_REPORT';

export const REQUEST_PRODUCT_RANGES_REPORT = 'REQUEST_PRODUCT_RANGES_REPORT';
export const RECEIVE_PRODUCT_RANGES_REPORT = 'RECEIVE_PRODUCT_RANGES_REPORT';
export const REQUEST_SALES_PRODUCTS_BY_RANGE_REPORT = 'REQUEST_SALES_PRODUCTS_BY_RANGE_REPORT';
export const RECEIVE_SALES_PRODUCTS_BY_RANGE_REPORT = 'RECEIVE_SALES_PRODUCTS_BY_RANGE_REPORT';

export const REQUEST_ADD_CARTON_TYPE = 'REQUEST_ADD_CARTON_TYPE';
export const REQUEST_CARTON_TYPE = 'REQUEST_CARTON_TYPE';
export const RECEIVE_CARTON_TYPE = 'RECEIVE_CARTON_TYPE';